version: '3.8'

services:
  # Frontend Development
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: todolist-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000}
      REACT_APP_CLERK_PUBLISHABLE_KEY: ${REACT_APP_CLERK_PUBLISHABLE_KEY}
      REACT_APP_ENVIRONMENT: ${REACT_APP_ENVIRONMENT:-development}
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: "0"
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Production (commented out by default)
  # Uncomment to use production build
  # frontend-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000}
  #       REACT_APP_CLERK_PUBLISHABLE_KEY: ${REACT_APP_CLERK_PUBLISHABLE_KEY}
  #       REACT_APP_ENVIRONMENT: production
  #   container_name: todolist-frontend-prod
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   healthcheck:
  #     test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
